export const CHANGE_DATE = 'CHANGE_DATE';
export const CHANGE_TIME = 'CHANGE_TIME';
export const CHANGE_UNAVAILABLE_TIME = 'CHANGE_UNAVAILABLE_TIME';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PHONE = 'CHANGE_PHONE';
export const CHANGE_USER = 'CHANGE_USER';
